#run docker-compose up -d
# Docker compose multi db
version: '3.1'

services: 

  mysqlsrv:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: teste
      MYSQL_USER: pepedev
      MYSQL_PASSWORD: minhasenhasecreta
    ports:
      - "3306:3306"
    networks:
    - multidb-compose-network

  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: pepedev
      POSTGRES_PASSWORD: minhasenhasecreta
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    networks:
      - multidb-compose-network
  
  mongodb:
    image: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    networks:
    - multidb-compose-network


  adminer:
    image: adminer
    restart: always
    ports: 
      - "8080:8080"
    networks:
      - multidb-compose-network
  
networks:
  multidb-compose-network:
    driver: bridge