#run docker-compose up -d
# Docker compose MySql
version: '3.1'

services: 

  mysqlsrv:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: teste
      MYSQL_USER: pepedev
      MYSQL_PASSWORD: minhasenhasecreta
    ports:
      - "3306:3306"
    networks:
    - postgres-compose-network

  adminer:
    image: adminer
    restart: always
    ports: 
      - "8080:8080"
    networks:
      - postgres-compose-network
  
networks:
  postgres-compose-network:
    driver: bridge